### ISSUE TITLE
Heartbeat to control peers

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollcast#1]
The client should be able to check if a server is up and running. Maybe via heartbeat ?

**Comment by mraspaud** [comment]
The server has to send a heartbeat (like every minute) in an independent thread. The client listens to the hearbeats of the connected servers, and using a timer, shouts if the heartbeat has not arrived.

**Comment by mraspaud** [comment]
Maybe implement a reconnection trial, and give the error message of the connection in case of failure.

**Comment by loerum** [comment]
A little comment: I think the heartbeat should be broadcasted (or multicasted), and should be send in the main loop (if it make sense), so hanging servers also can be detected.

**Comment by mraspaud** [comment]
Since the servers are most likely spread on different networks, I am not sure multicasting or broadcasting is in order. We're working on this at the moment, and the solution is to use the "have" message publisher to send heartbeats.
